// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesBlogRazor.WebApp.Models;

namespace MoviesBlogRazor.WebApp.Migrations
{
    [DbContext(typeof(MoviesBlogRazorContext))]
    [Migration("20200222113542_AddConfigurations")]
    partial class AddConfigurations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MoviesBlogRazor.WebApp.Models.MovieReview", b =>
                {
                    b.Property<int>("MovieReviewId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Genre")
                        .HasMaxLength(255);

                    b.Property<string>("Image");

                    b.Property<int?>("MyRating");

                    b.Property<decimal?>("Rating");

                    b.Property<DateTime?>("ReleaseDate");

                    b.Property<string>("Review");

                    b.Property<DateTime?>("ReviewDateCreated");

                    b.Property<string>("Title")
                        .HasMaxLength(255);

                    b.HasKey("MovieReviewId");

                    b.ToTable("MovieReview");
                });

            modelBuilder.Entity("MoviesBlogRazor.WebApp.Models.Quote", b =>
                {
                    b.Property<int>("QuoteId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MovieTitle")
                        .HasMaxLength(255);

                    b.Property<string>("Text");

                    b.HasKey("QuoteId");

                    b.ToTable("Quote");

                    b.HasData(
                        new
                        {
                            QuoteId = 1,
                            MovieTitle = "Fight Club (1999)",
                            Text = "The first rule of Fight Club is: You do not talk about Fight Club. The second rule of Fight Club is: You do not talk about Fight Club."
                        },
                        new
                        {
                            QuoteId = 2,
                            MovieTitle = "Pride & Prejudice (2005)",
                            Text = "He is just what a young man ought to be."
                        },
                        new
                        {
                            QuoteId = 3,
                            MovieTitle = "The Green Mile (1999)",
                            Text = "Time takes it all, whether you want it to or not."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
